FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install --no-install-recommends --yes \
       ca-certificates clang curl gcc gzip make python3 tar \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

